

const books = [
  {
    id: "1",
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi",
    src:"./src/Components/images/dune.jpg",
    description: "Epic science fiction novel.",
    rating: 4.8,
  },
  {
    id: "2",
    title: "1984",
    author: "George Orwell",
    category: "Fiction",
    src:"./src/Components/images/1984.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "3",
    title: "The Women",
    author: "Kristain Hannah",
    category: "Fiction",
    src:"./src/Components/images/women.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "4",
    title: "Girl Dinner",
    author: "Olivie Blank",
    category: "Fiction",
    src:"./src/Components/images/girl.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "5",
    title: "Uncharmed",
    author: "Lucy Jane",
    category: "Fiction",
    src:"./src/Components/images/uncharm.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "6",
    title: "The Golden Road",
    author: "William Dalry",
    category: "Non-Fiction",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "7",
    title: "Atomic Habits",
    author: "James Clear",
    category: "Non-Fiction",
    src:"./src/Components/images/atom.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "8",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Non-Fiction",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "9",
    title: "Amazing Worlds",
    author: "Keith cooper",
    category: "Sci-Fi",
    src:"./src/Components/images/ama.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "10",
    title: "Children of Time",
    author: "Adrian",
    category: "Sci-Fi",
    src:"./src/Components/images/child.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "11",
    title: "The Rig",
    author: "Roger Levy",
    category: "Sci-Fi",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "12",
    title: "I Will Always Love You",
    author: "Arpita Debanath",
    category: "Romance",
    src:"./src/Components/images/i will.png",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "13",
    title: "If I never met you",
    author: "Mhairi McFaraiane",
    category: "Romance",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "14",
    title: "Technically yours",
    author: "Denise williams",
    category: "Romance",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "15",
    title: "Agatha Oddly",
    author: "Lena Jones",
    category: "Mystery",
    src:"./src/Components/images/agatha.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "16",
    title: "Truly Devious",
    author: "Maureen Johnson",
    category: "Mystery",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "17",
    title: "The Girl in the House",
    author: "Harshavardhan Rao",
    category: "Mystery",
    src:".src/Components/images/girl.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "18",
    title: "the sun and her flowers",
    author: "Rupi kaur",
    category: "Poetry",
    src:"./src/Components/images/sun.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "19",
    title: "Petals of healing",
    author: "Anne raynoe",
    category: "Poetry",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "20",
    title: "Where the sidewalk Ends",
    author: "Shel Silverstein",
    category: "Poetry",
    src:"./src/Components/images/Ends.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "21",
    title: "Harry Potter",
    author: "J.K.Rowling",
    category: "Fiction",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "22",
    title: "The midnight library",
    author: "Matt Haig",
    category: "Fiction",
    src:"./src/Components/images/mid.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "23",
    title: "The Rose Maker",
    author: "Alex Leu",
    category: "Sci-Fi",
    src:"./src/Components/images/dune.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  },
  {
    id: "24",
    title: "Through Stranger Eyes",
    author: "Chris Saran",
    category: "Sci-Fi",
    src:"./src/Components/images/stran.jpg",
    description: "Dystopian novel.",
    rating: 4.7,
  }

];

export default books;
